# Generated by Django 2.2 on 2018-11-16 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_end', to='ASP.Location')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_start', to='ASP.Location')),
            ],
        ),
    ]
