# Generated by Django 2.2 on 2018-11-16 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASP', '0002_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP.UserData')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP.UserData')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('priority', models.CharField(choices=[('3', 'High'), ('2', 'Medium'), ('1', 'Low')], default='3', max_length=1)),
                ('status', models.CharField(choices=[('QP', 'Queued for Processing'), ('PW', 'Processing by Warehouse'), ('QD', 'Queued for Dispatch'), ('DI', 'Dispatched'), ('DE', 'Delivered')], default='QP', max_length=2)),
                ('timeQP', models.DateTimeField()),
                ('timePW', models.DateTimeField(null=True)),
                ('timeQD', models.DateTimeField(null=True)),
                ('timeDI', models.DateTimeField(null=True)),
                ('timeDE', models.DateTimeField(null=True)),
                ('clinic_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP.ClinicManager')),
                ('dispatcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ASP.Dispatcher')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP.Location')),
            ],
        ),
    ]
