# Generated by Django 2.2 on 2018-11-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASP', '0004_remove_userdata_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='last_name',
        ),
    ]
